### ISSUE TITLE
Automatically install `.d.ts` types for imported snippets when someone runs `snippets dev ./path/to/snippets.tsx`

### ISSUE THREAD

**Issue by seveibar** [tscircuit/snippets-cli#3]
- [ ] Automatically populate `node_modules/@tsci/seveibar.red-led/index.d.ts` with the content from the snippets api (`snippet.dts`), creating directories where necessary

/bounty $20

**Comment by ShiboSoftwareDev** [comment]
@seveibar how do i access the snippets api? is is the registry-api?

**Comment by seveibar** [comment]
@ShiboSoftwareDev sorry for the delay, yes it's the registry api!

**Comment by seveibar** [comment]
@ShiboSoftwareDev it shouldn't be needed but there's also a config manager that let's you access the auth token from the original cli

**Comment by ShiboSoftwareDev** [comment]
I injected the types, but they are not known inside the project, @seveibar 
![Image](https://github.com/user-attachments/assets/23163741-f198-4992-9e67-04f0e56dcdac)

**Comment by ShiboSoftwareDev** [comment]
this is how the files look
![Image](https://github.com/user-attachments/assets/d8ff0752-08f7-4d1c-b9b7-beb9e3ada384)

**Comment by seveibar** [comment]
@ShiboSoftwareDev hmm not sure, we might need to put in a package json file too

**Comment by ShiboSoftwareDev** [comment]
@seveibar I had one but maybe it's missing something, I don't have to do bun add don't I?
 ![Image](https://github.com/user-attachments/assets/388e2dfc-f741-4341-90d8-be4e0ca1343d)

**Comment by seveibar** [comment]
Maybe set the main entry to "index.js"?

**Comment by seveibar** [comment]
Technically you could insert the registry .npmrc and fully install the package normally with "bun add". That is acceptable but wont fix type issues because the registry may not support returning types (or it might not sure)

**Comment by seveibar** [comment]
![image](https://github.com/user-attachments/assets/f2e3eed3-025c-476d-b7c6-152091a2fa01)

**Comment by seveibar** [comment]
That full package installation isnt a bad idea to do even if its currently broken because it'll allow for theoretical future execution. The downside is you have to call to shell and npm installation is technically insecure

**Comment by seveibar** [comment]
I guess im ok with either i guess but if you do installation i would make sure the code is pretty rock solid because itll will have operating system and runtime bugs....

It might be nice to have the minimal types version...

**Comment by ShiboSoftwareDev** [comment]
I'll see what I can do

**Comment by ShiboSoftwareDev** [comment]
@seveibar today it worked without I do anything, maybe removing the old test files caused a bug in my editor

**Comment by ShiboSoftwareDev** [comment]
@seveibar this is the content from the fetched dts:
![Image](https://github.com/user-attachments/assets/746474a5-659b-4f58-bd14-065f09a041f5)
does it look correct?
